version: '3'
services:
  app:
    container_name: basil
    build:
      context: .
    volumes:
      - app_data:/app:consistent
      - /app/node_modules
      - /app/backend/node_modules
      - /app/frontend/node_modules
    ports:
      - '3000:3000'
      - '3001:3001'
    command: npm run docker:dev
volumes:
  app_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
