version: '3'
services:
  app:
    container_name: basil
    build:
      context: .
    volumes:
      - ./:/app:consistent
      - /app/node_modules
      - /app/backend/node_modules
      - /app/frontend/node_modules
    ports:
      - '3000:3000'
      - '3001:3001'
    command: npm run docker:dev
